# Generated by Django 4.1.4 on 2023-02-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desctiption',
            new_name='description',
        ),
    ]
